apiVersion: v1
#  这个指的是我 k8s 有哪些 volume
kind: PersistentVolume
metadata:
  name: webook-live-mysql-claim
spec:
  storageClassName: muanual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/live"

