apiVersion: v1
#  这个指的是我 k8s 有哪些 volume
kind: PersistentVolume
metadata:
  name: webook-mysql-claim-pv-v1
spec:
  # 要与 pvc 的对应
  storageClassName: muanualv1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/live"
